/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.telas;

import dao.ClienteDAO;
import gui.tabelas.ClienteTableModel;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import modelo.Cliente;

/**
 *
 * @author user
 */
public class TelaBuscarCliente extends javax.swing.JDialog {

    /**
     * Creates new form TelaBuscaCliente
     */
    JInternalFrame parent;

    public TelaBuscarCliente(JInternalFrame parent) {
        super();
        this.parent = parent;
        initComponents();
        carregarTabela();
    }

    private void carregarTabela() {
        try {
            ClienteDAO clienteDAO = new ClienteDAO();
            ClienteTableModel ctm = (ClienteTableModel) tbClientes.getModel();
            ctm.setDados(clienteDAO.BuscarTodos());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar tabela de clientes.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnNome = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        spTabelaClientes = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de busca de cliente");

        lbNome.setText("Nome:");
        pnNome.add(lbNome);

        txtNome.setToolTipText("Nome do cliente");
        txtNome.setMinimumSize(new java.awt.Dimension(300, 25));
        txtNome.setPreferredSize(new java.awt.Dimension(300, 25));
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });
        pnNome.add(txtNome);

        getContentPane().add(pnNome, java.awt.BorderLayout.PAGE_START);

        tbClientes.setAutoCreateRowSorter(true);
        tbClientes.setModel(new ClienteTableModel());
        tbClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClientesMouseClicked(evt);
            }
        });
        spTabelaClientes.setViewportView(tbClientes);

        getContentPane().add(spTabelaClientes, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(627, 355));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased
        TableRowSorter rs = (TableRowSorter) tbClientes.getRowSorter();
        rs.setRowFilter(RowFilter.regexFilter("(?i)" + txtNome.getText(), 0, 1));
    }//GEN-LAST:event_txtNomeKeyReleased

    private void tbClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClientesMouseClicked
        if (evt.getClickCount() == 2) {
            ClienteTableModel ctm = (ClienteTableModel) tbClientes.getModel();
            int linhaSelecionada = tbClientes.getRowSorter().convertRowIndexToModel(tbClientes.getSelectedRow());
            Cliente cliente = ctm.getRowValue(linhaSelecionada);

            if (parent instanceof TelaLancamentoVenda) {
                TelaLancamentoVenda lv = (TelaLancamentoVenda) parent;
                lv.setCliente(cliente);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Campo de destino inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            }

        }
    }//GEN-LAST:event_tbClientesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbNome;
    private javax.swing.JPanel pnNome;
    private javax.swing.JScrollPane spTabelaClientes;
    private javax.swing.JTable tbClientes;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
