/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.telas;

import dao.VendaDAO;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Venda;

/**
 *
 * @author user
 */
public class TelaMovimentoVendas extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaMovimentoVendas
     */
    public TelaMovimentoVendas() {
        initComponents();
        carregarTabelaVendas();
    }

    private void carregarImagens() {
        ImageIcon buscar = new ImageIcon(getClass().getResource("/gui/icones/buscar.png"));
        btnBuscarVenda.setIcon(buscar);

        ImageIcon imprimir = new ImageIcon(getClass().getResource("/gui/icones/imprimir.png"));
        btnImprimir.setIcon(imprimir);

        ImageIcon cancelar = new ImageIcon(getClass().getResource("/gui/icones/cancel.png"));
        btnCancelar.setIcon(cancelar);

    }

    DefaultTableModel tbVendas = new DefaultTableModel(null, new String[]{
        "Cliente", "Data", "Valor", "Situação"
    });

    private void carregarTabelaVendas() {
        while (tbVendas.getRowCount() > 0) {
            tbVendas.removeRow(0);
        }
        VendaDAO vendaDAO = new VendaDAO();
        List<Venda> vendas = vendaDAO.BuscarTodos();
        String campos[] = new String[]{null, null, null, null};
        for (int i = 0; i < vendas.size(); i++) {
            tbVendas.addRow(campos);
            tbVendas.setValueAt(vendas.get(i).getIdVenda(), i, 0);
            tbVendas.setValueAt(vendas.get(i).getDataVenda(), i, 1);
            tbVendas.setValueAt(vendas.get(i).getValorTotalVenda(), i, 2);
            tbVendas.setValueAt(vendas.get(i).getSituacao(), i, 3);
        }
    }

    private void carregarTabelaVendasPorIntervaloDeData() {
        try {
            while (tbVendas.getRowCount() > 0) {
                tbVendas.removeRow(0);
            }
            VendaDAO vendaDAO = new VendaDAO();
            java.sql.Date dataInicio = new java.sql.Date(jDataInicio.getDate().getTime());
            java.sql.Date dataFim = new java.sql.Date(jDataFim.getDate().getTime());

            List<Venda> vendas = vendaDAO.buscarPorIntervaloDatas(dataInicio, dataFim);
            if (vendas.size() < 1) {
                JOptionPane.showMessageDialog(null, "Não foi encontrado nenhuma venda entre : " + dataInicio + " e " + dataFim);
            }

            String campos[] = new String[]{null, null, null, null};
            for (int i = 0; i < vendas.size(); i++) {
                tbVendas.addRow(campos);
                tbVendas.setValueAt(vendas.get(i).getIdVenda(), i, 0);
                tbVendas.setValueAt(vendas.get(i).getDataVenda(), i, 1);
                tbVendas.setValueAt(vendas.get(i).getValorTotalVenda(), i, 2);
                tbVendas.setValueAt(vendas.get(i).getSituacao(), i, 3);
            }
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Datas Inválidas!", "Pesquisar Data", JOptionPane.ERROR_MESSAGE);
            carregarTabelaVendas();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbDataInicio = new javax.swing.JLabel();
        jDataInicio = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jDataFim = new com.toedter.calendar.JDateChooser();
        btnBuscarVenda = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnImprimir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Movimento de Vendas");
        setToolTipText("");

        lbDataInicio.setText("Data de início:");
        jPanel1.add(lbDataInicio);

        jDataInicio.setMinimumSize(new java.awt.Dimension(150, 25));
        jDataInicio.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel1.add(jDataInicio);

        jLabel2.setText("Data de fim:");
        jPanel1.add(jLabel2);

        jDataFim.setMinimumSize(new java.awt.Dimension(150, 25));
        jDataFim.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel1.add(jDataFim);

        btnBuscarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icones/buscar.png"))); // NOI18N
        btnBuscarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVendaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarVenda);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icones/imprimir.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setMaximumSize(new java.awt.Dimension(115, 45));
        btnImprimir.setMinimumSize(new java.awt.Dimension(115, 45));
        btnImprimir.setPreferredSize(new java.awt.Dimension(115, 45));
        jPanel2.add(btnImprimir);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icones/cancel.png"))); // NOI18N
        btnCancelar.setText("Fechar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(107, 45));
        btnCancelar.setMinimumSize(new java.awt.Dimension(107, 45));
        btnCancelar.setPreferredSize(new java.awt.Dimension(107, 45));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jTable1.setModel(tbVendas);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVendaActionPerformed
        carregarTabelaVendasPorIntervaloDeData();
    }//GEN-LAST:event_btnBuscarVendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarVenda;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnImprimir;
    private com.toedter.calendar.JDateChooser jDataFim;
    private com.toedter.calendar.JDateChooser jDataInicio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbDataInicio;
    // End of variables declaration//GEN-END:variables
}
